services:
    radarr:
        container_name: radarr
        image: lscr.io/linuxserver/radarr:latest
        ports:
            - "7878:7878"
        environment:
            - PUID=1000
            - PGID=1000
            # - PUID=502 # Use a User ID that has permissions on the volumes below
            # - PGID=20 # Use a Group ID that has permissions on the volumes below
            # - UMASK=002
            # - UMASK=022
            - TZ=Asia/Bangkok
        volumes:
            - /Volumes/Pteri/torrent_fiesta/radarr/config:/config
            - /Volumes/Pteri/torrent_fiesta/data:/data
            - /Volumes/Pteri/torrent_fiesta/data/torrents:/data/torrents
