services:
    sonarr:
        container_name: sonarr
        image: lscr.io/linuxserver/sonarr:latest
        ports:
            - "8989:8989"
        environment:
            - PUID=1000
            - PGID=1000
            # - PUID=502 # Use a User ID that has permissions on the volumes below
            # - PGID=20 # Use a Group ID that has permissions on the volumes below
            # - UMASK=002
            - TZ=Asia/Bangkok # User your timezone or UTC
        volumes:
            - /Volumes/Pteri/torrent_fiesta/sonarr/config:/config
            - /Volumes/Pteri/torrent_fiesta/data:/data
            - /Volumes/Pteri/torrent_fiesta/data/torrents:/data/torrents
            - /Volumes/Pteri/Torrents/SonarrTV:/imports
